import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  layout("routes/_storefront.tsx", [
    index("routes/_index.tsx"),
    route("products", "routes/products._index.tsx"),
    route("products/:slug", "routes/products.$slug.tsx"),
    route("category/:slug", "routes/category.$slug.tsx"),
    route("cart", "routes/cart.tsx"),
    route("checkout", "routes/checkout.tsx"),
    route("account", "routes/account.tsx"),
    route("account/wishlist", "routes/account.wishlist.tsx"),
    route("account/addresses", "routes/account.addresses.tsx"),
    route("orders", "routes/orders._index.tsx"),
    route("orders/:id", "routes/orders.$id.tsx"),
    route("auth/login", "routes/auth.login.tsx"),
    route("auth/register", "routes/auth.register.tsx"),
    route("auth/forgot-password", "routes/auth.forgot-password.tsx"),
    route("auth/reset-password", "routes/auth.reset-password.tsx"),
    route("blog", "routes/blog._index.tsx"),
    route("blog/:slug", "routes/blog.$slug.tsx"),
    route("about", "routes/about.tsx"),
    route("contact", "routes/contact.tsx"),
    route("thank-you", "routes/thank-you.tsx"),
    route("deals", "routes/deals.tsx"),
    route("*", "routes/$.tsx"),
  ]),
  layout("routes/admin/_admin.tsx", [
    route("admin/dashboard", "routes/admin/dashboard.tsx"),
    route("admin/products", "routes/admin/products._index.tsx"),
    route("admin/orders", "routes/admin/orders._index.tsx"),
    route("admin/customers", "routes/admin/customers._index.tsx"),
    route("admin/coupons", "routes/admin/coupons._index.tsx"),
    route("admin/newsletter", "routes/admin/newsletter._index.tsx"),
  ]),
] satisfies RouteConfig;
