// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:slug": {
    params: {
      "slug": string;
    };
  };
  "/category/:slug": {
    params: {
      "slug": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/account/wishlist": {
    params: {};
  };
  "/account/addresses": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/auth/forgot-password": {
    params: {};
  };
  "/auth/reset-password": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/thank-you": {
    params: {};
  };
  "/deals": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/products": {
    params: {};
  };
  "/admin/orders": {
    params: {};
  };
  "/admin/customers": {
    params: {};
  };
  "/admin/coupons": {
    params: {};
  };
  "/admin/newsletter": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/products/:slug" | "/category/:slug" | "/cart" | "/checkout" | "/account" | "/account/wishlist" | "/account/addresses" | "/orders" | "/orders/:id" | "/auth/login" | "/auth/register" | "/auth/forgot-password" | "/auth/reset-password" | "/blog" | "/blog/:slug" | "/about" | "/contact" | "/thank-you" | "/deals" | "/*" | "/admin/dashboard" | "/admin/products" | "/admin/orders" | "/admin/customers" | "/admin/coupons" | "/admin/newsletter";
  };
  "routes/_storefront.tsx": {
    id: "routes/_storefront";
    page: "/" | "/products" | "/products/:slug" | "/category/:slug" | "/cart" | "/checkout" | "/account" | "/account/wishlist" | "/account/addresses" | "/orders" | "/orders/:id" | "/auth/login" | "/auth/register" | "/auth/forgot-password" | "/auth/reset-password" | "/blog" | "/blog/:slug" | "/about" | "/contact" | "/thank-you" | "/deals" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/products._index.tsx": {
    id: "routes/products._index";
    page: "/products";
  };
  "routes/products.$slug.tsx": {
    id: "routes/products.$slug";
    page: "/products/:slug";
  };
  "routes/category.$slug.tsx": {
    id: "routes/category.$slug";
    page: "/category/:slug";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/account.wishlist.tsx": {
    id: "routes/account.wishlist";
    page: "/account/wishlist";
  };
  "routes/account.addresses.tsx": {
    id: "routes/account.addresses";
    page: "/account/addresses";
  };
  "routes/orders._index.tsx": {
    id: "routes/orders._index";
    page: "/orders";
  };
  "routes/orders.$id.tsx": {
    id: "routes/orders.$id";
    page: "/orders/:id";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/auth.forgot-password.tsx": {
    id: "routes/auth.forgot-password";
    page: "/auth/forgot-password";
  };
  "routes/auth.reset-password.tsx": {
    id: "routes/auth.reset-password";
    page: "/auth/reset-password";
  };
  "routes/blog._index.tsx": {
    id: "routes/blog._index";
    page: "/blog";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/thank-you.tsx": {
    id: "routes/thank-you";
    page: "/thank-you";
  };
  "routes/deals.tsx": {
    id: "routes/deals";
    page: "/deals";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
  "routes/admin/_admin.tsx": {
    id: "routes/admin/_admin";
    page: "/admin/dashboard" | "/admin/products" | "/admin/orders" | "/admin/customers" | "/admin/coupons" | "/admin/newsletter";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin/products._index.tsx": {
    id: "routes/admin/products._index";
    page: "/admin/products";
  };
  "routes/admin/orders._index.tsx": {
    id: "routes/admin/orders._index";
    page: "/admin/orders";
  };
  "routes/admin/customers._index.tsx": {
    id: "routes/admin/customers._index";
    page: "/admin/customers";
  };
  "routes/admin/coupons._index.tsx": {
    id: "routes/admin/coupons._index";
    page: "/admin/coupons";
  };
  "routes/admin/newsletter._index.tsx": {
    id: "routes/admin/newsletter._index";
    page: "/admin/newsletter";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_storefront": typeof import("./app/routes/_storefront.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/products._index": typeof import("./app/routes/products._index.tsx");
  "routes/products.$slug": typeof import("./app/routes/products.$slug.tsx");
  "routes/category.$slug": typeof import("./app/routes/category.$slug.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/account.wishlist": typeof import("./app/routes/account.wishlist.tsx");
  "routes/account.addresses": typeof import("./app/routes/account.addresses.tsx");
  "routes/orders._index": typeof import("./app/routes/orders._index.tsx");
  "routes/orders.$id": typeof import("./app/routes/orders.$id.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/auth.forgot-password": typeof import("./app/routes/auth.forgot-password.tsx");
  "routes/auth.reset-password": typeof import("./app/routes/auth.reset-password.tsx");
  "routes/blog._index": typeof import("./app/routes/blog._index.tsx");
  "routes/blog.$slug": typeof import("./app/routes/blog.$slug.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/thank-you": typeof import("./app/routes/thank-you.tsx");
  "routes/deals": typeof import("./app/routes/deals.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
  "routes/admin/_admin": typeof import("./app/routes/admin/_admin.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/products._index": typeof import("./app/routes/admin/products._index.tsx");
  "routes/admin/orders._index": typeof import("./app/routes/admin/orders._index.tsx");
  "routes/admin/customers._index": typeof import("./app/routes/admin/customers._index.tsx");
  "routes/admin/coupons._index": typeof import("./app/routes/admin/coupons._index.tsx");
  "routes/admin/newsletter._index": typeof import("./app/routes/admin/newsletter._index.tsx");
};