// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products": {
    params: {};
  };
  "/products/:slug": {
    params: {
      "slug": string;
    };
  };
  "/category/:slug": {
    params: {
      "slug": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/account": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/orders/:id": {
    params: {
      "id": string;
    };
  };
  "/auth/login": {
    params: {};
  };
  "/auth/register": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:slug": {
    params: {
      "slug": string;
    };
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/thank-you": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/products": {
    params: {};
  };
  "/admin/orders": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/products" | "/products/:slug" | "/category/:slug" | "/cart" | "/checkout" | "/account" | "/orders" | "/orders/:id" | "/auth/login" | "/auth/register" | "/blog" | "/blog/:slug" | "/about" | "/contact" | "/thank-you" | "/admin/dashboard" | "/admin/products" | "/admin/orders" | "/admin/users" | "/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/products._index.tsx": {
    id: "routes/products._index";
    page: "/products";
  };
  "routes/products.$slug.tsx": {
    id: "routes/products.$slug";
    page: "/products/:slug";
  };
  "routes/category.$slug.tsx": {
    id: "routes/category.$slug";
    page: "/category/:slug";
  };
  "routes/cart.tsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/checkout.tsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/account.tsx": {
    id: "routes/account";
    page: "/account";
  };
  "routes/orders._index.tsx": {
    id: "routes/orders._index";
    page: "/orders";
  };
  "routes/orders.$id.tsx": {
    id: "routes/orders.$id";
    page: "/orders/:id";
  };
  "routes/auth.login.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/auth.register.tsx": {
    id: "routes/auth.register";
    page: "/auth/register";
  };
  "routes/blog._index.tsx": {
    id: "routes/blog._index";
    page: "/blog";
  };
  "routes/blog.$slug.tsx": {
    id: "routes/blog.$slug";
    page: "/blog/:slug";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/thank-you.tsx": {
    id: "routes/thank-you";
    page: "/thank-you";
  };
  "routes/admin/dashboard.tsx": {
    id: "routes/admin/dashboard";
    page: "/admin/dashboard";
  };
  "routes/admin/products._index.tsx": {
    id: "routes/admin/products._index";
    page: "/admin/products";
  };
  "routes/admin/orders._index.tsx": {
    id: "routes/admin/orders._index";
    page: "/admin/orders";
  };
  "routes/admin/users._index.tsx": {
    id: "routes/admin/users._index";
    page: "/admin/users";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/products._index": typeof import("./app/routes/products._index.tsx");
  "routes/products.$slug": typeof import("./app/routes/products.$slug.tsx");
  "routes/category.$slug": typeof import("./app/routes/category.$slug.tsx");
  "routes/cart": typeof import("./app/routes/cart.tsx");
  "routes/checkout": typeof import("./app/routes/checkout.tsx");
  "routes/account": typeof import("./app/routes/account.tsx");
  "routes/orders._index": typeof import("./app/routes/orders._index.tsx");
  "routes/orders.$id": typeof import("./app/routes/orders.$id.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login.tsx");
  "routes/auth.register": typeof import("./app/routes/auth.register.tsx");
  "routes/blog._index": typeof import("./app/routes/blog._index.tsx");
  "routes/blog.$slug": typeof import("./app/routes/blog.$slug.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/thank-you": typeof import("./app/routes/thank-you.tsx");
  "routes/admin/dashboard": typeof import("./app/routes/admin/dashboard.tsx");
  "routes/admin/products._index": typeof import("./app/routes/admin/products._index.tsx");
  "routes/admin/orders._index": typeof import("./app/routes/admin/orders._index.tsx");
  "routes/admin/users._index": typeof import("./app/routes/admin/users._index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};